apiVersion: apps/v1
kind: deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
  matchLabels: production
  replicas: 3
  template: 
    metadata:
      name: nginx
      labels: 
        env: production
    spec: 
      containers:
      - name: nginx
        image: nginx